BasketBallASPNET/Controllers/ClubController.cs
using BasketBallASPNET.Models;
using BusnLogic;
using DALException;
using DALMSSQLServer;
using Microsoft.AspNetCore.Mvc;

namespace BasketBallASPNET.Controllers
{
    public class ClubController : Controller
    {
        private ClubContainer ClubContainer = new ClubContainer(new ClubMSSQLDAL());
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("LoggedIn") == 1)
            {
                try
                {
                    List<Club> Lc = ClubContainer.GetAll();
                    List<ClubVM> Lvm = new List<ClubVM>();
                    foreach (Club c in Lc)
                    {
                        Lvm.Add(new ClubVM(c.ID, c.Name));
                    }
                    return View(Lvm);
                }
                catch (TemporaryExceptionDAL ex)
                {
                    ViewBag.Error = ex.Message + " PLS try again later";
                    return RedirectToAction("Error", "Home");
                }
                catch (PermanentExceptionDAL ex)
                {
                    return Content(ex.Message);
                }

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            
        }

        public IActionResult Team()
        {
            return RedirectToAction("Index", "TeamController");
        }
    }
}

BasketBallASPNET/Views/Shared/Help.cshtml
@{
    ViewData["Title"] = "Help";
}

<h1>BasketBal Bond</h1>
<p>Deze pagina is voor het helpen met de Basketbal App.</p><br />
<p>Check of je internet verbinding goed is. Ben je vebonden met de VPN?</p>
<p>Bent u ingelogd met het goede account?</p>
<p>Ziet niet uw wedstrijden, Clubs, Teams? Refresh pagina of log opnieuw in.</p>
<hr/>
<div class="row">
    <div class="col-md-10 col-md-push-1">
        <div class="alert alert-info">
            <h3>Neem Contact op<i class="fa fa-warning pull-right"></i></h3>
            Als je geen vragen helpt over het programma maar over een probleem,<br/>
            neem dan contact met ons op <a href="https://www.basketball.nl/organisatie/contact/">https://www.basketball.nl/organisatie/contact/</a>.
        </div>
    </div>
</div>

BasketBallASPNET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasketBallASPNET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BasketBallASPNET.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md nav-pills py-3 navbar-toggleable-md border-bottom box-shadow mb-3 BasketballMainTheme">

            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BasketBal Bond</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">

                    <span class="navbar-toggler-icon"></span>

                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">

                    <ul class="navbar-nav  flex-grow-1 ">

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Club" asp-action="Index"> Clubs</a>
                        </li>
                        @if (@Context.Session.GetInt32("RoleID") == 1)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" style="color: aliceblue;" data-bs-toggle="dropdown" href="#">Wedstrijd</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" style="color: black; " asp-area="" asp-controller="Wedstrijd" asp-action="Index"> Wedstrijd</a></li>
                                    <li> <a class="dropdown-item" style="color: black; " asp-controller="Wedstrijd" asp-action="Create"> Wedstrijd Inplannen</a></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li><a class="nav-link " asp-area="" asp-controller="Wedstrijd" asp-action="Index"> Wedstrijd</a></li>
                        }

                    </ul>
                    <ul class="navbar-nav ">
                        <li>
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Help"> help</a>
                        </li>
                        <li class="nav-item justify-content-end">
                            @if (Context.Session.GetInt32("LoggedIn") == 1)
                            {
                                <button class="btn btn-link " style="text-decoration:none; color: aliceblue;" type="button" data-bs-toggle="offcanvas" data-bs-target="#demo">
                                    @Context.Session.GetString("Name")
                                </button>
                            }
                            else
                            {
                                <a class="nav-link " asp-area="" asp-controller="Account" asp-action="login"> Account</a>
                            }

                        </li>

                    </ul>



                </div>

            </div>

        </nav>
        <div class="offcanvas offcanvas-end" id="demo">
            <div class="offcanvas-header">
                <h1 class="offcanvas-title">@Context.Session.GetString("Name")</h1>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
            </div>
            <div class="offcanvas-body">
                <p>Club: @Context.Session.GetString("ClubName")</p>
                <p>Team: @Context.Session.GetString("TeamName")</p>
                <p>SpelerNummer: @Context.Session.GetInt32("SpelerNummer")</p>
                <button type="button" class="btn btn-outline-primary" onclick="location.href='@Url.Action("Logout", "Account")'">Logout</button>
            </div>
        </div>
    </header>

    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">

        <div class="container-fluid">
            &copy; 2022 - BasketBallASPNET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>